name: build

on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - '*'

jobs:
  ci-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/cache@v2
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
      - uses: actions/setup-go@v2
        with:
          go-version: 1.14
      - name: Build
        run: make all
      - name: Upload codecov coverage
        uses: codecov/codecov-action@v1.0.10
        with:
          file: ./coverage.out
      - name: Upload coverage
        uses: actions/upload-artifact@v2
        with:
          name: coverage
          path: coverage.*
      - id: git-auto-tag
        name: Bump version and push tag
        uses: anothrNick/github-tag-action@1.22.0
        if: github.ref == 'refs/heads/master'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WITH_V: true
          DEFAULT_BUMP: patch
      - run: git tag ${{ steps.git-auto-tag.outputs.new_tag }}
        if: github.ref == 'refs/heads/master'
      - name: Release
        if: github.ref == 'refs/heads/master'
        run: make release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload dist
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist
